### ISSUE TITLE
Einstellungsfenster

### ISSUE THREAD

**Issue by MickyRosa** [Madmaeckes/VTfx#10]
Einstellungen sollten vorerst enthalten:
- Maßstab  ->  typische Maßstäbe ([https://rechneronline.de/modelleisenbahnen/](url)) + benutzerdefinierte
- Betriebsart (Kreisverkehr / Pendelverkehr)
- Farbgebung

_Übernahmen aus altem Code möglich_

**Comment by Madmaeckes** [comment]
#### TODO:

**Colorpicker für die Digitalanzeige:**
 GuiAktualisieren besitzt Methode setFarbeFuerDigitalanzeige() mit der die neue Farbe gesetzt werden kann.

**Comment by Madmaeckes** [comment]
Neues Todo: checkbox ob gleisabschnitte automatisch erkannt werden sollen
