### ISSUE TITLE
GuiAktualisieren erstellen

### ISSUE THREAD

**Issue by Madmaeckes** [Madmaeckes/VTfx#12]
Eine Klasse GuiAktualisieren erstellen um aktualisierungen auf der Benutzeroberfläche praktisch durchführen zu können.

**Comment by Madmaeckes** [comment]
**GuiAktualisieren kann bis jetzt:**

Verbindungsstatus:
-     "Verbunden",
-     "Verbindung herstellen...",
-     "Getrennt",
-     "Verbindung trennen..."


**Ausstehend:**

Messungsstatus:
-     "Messung vorbereiten...",
-     "Messung läuft..." (+Zeit),
-     ("Messung pausiert"),
-     "Messung beendet",
-     "Messung abgebrochen" (weil Verbindung abgerissen)
-

**Comment by Madmaeckes** [comment]
**GuiAktualisieren kann bis jetzt:**

Verbindungsstatus:
-     "Verbunden",
-     "Verbindung herstellen...",
-     "Getrennt",
-     "Verbindung trennen..."

**Ausstehend:**

Messungsstatus:
-     "Messung vorbereiten...",
-     "Messung läuft..." (+Zeit),
-     ("Messung pausiert"),
-     "Messung beendet",
-     "Messung abgebrochen" (weil Verbindung abgerissen)

**Comment by Madmaeckes** [comment]
**GuiAktualisieren kann bis jetzt:**

Verbindungsstatus:
-     "Verbunden",
-     "Verbindung herstellen...",
-     "Getrennt",
-     "Verbindung trennen..."

Geschwindigkeitsanzeige:
- setMomentaneGeschw()

**Ausstehend:**

Messungsstatus:
-     "Messung vorbereiten...",
-     "Messung läuft..." (+Zeit),
-     ("Messung pausiert"),
-     "Messung beendet",
-     "Messung abgebrochen" (weil Verbindung abgerissen)

**Comment by Madmaeckes** [comment]
**GuiAktualisieren kann bis jetzt:**

Verbindungsstatus:
-     "Verbunden",
-     "Verbindung herstellen...",
-     "Getrennt",
-     "Verbindung trennen..."

Geschwindigkeitsanzeige:
- setMomentaneGeschw()
- markiereTabellenZeile()

**Ausstehend:**

Messungsstatus:
-     "Messung vorbereiten...",
-     "Messung läuft..." (+Zeit),
-     ("Messung pausiert"),
-     "Messung beendet",
-     "Messung abgebrochen" (weil Verbindung abgerissen)

**Comment by MickyRosa** [comment]
abgebrochene Messung wegen Verbindungsabbruch in Statusmeldung berücksichtigt
roterKreis-fix bei trennen-/Messung-beenden-Button
