### ISSUE TITLE
Statusleiste

### ISSUE THREAD

**Issue by MickyRosa** [Madmaeckes/VTfx#2]
- Button zum starten/stoppen der Messung
- Statusleiste
  auf der GUI platzieren

**Comment by Madmaeckes** [comment]
Was soll in die statusleiste?
Eine Verbindung bauen wir ja garnichtmehr auf.

**Comment by MickyRosa** [comment]
Doch tun wir, zum messen.

**Comment by MickyRosa** [comment]
@Statusleiste muss die folgenden Status farbig anzeigen können:
- Verbindungsstatus:
  "Verbunden",
  "Verbindung herstellen...",
  "Getrennt",
  "Verbindung trennen..."
- Messungsstatus
  "Messung vorbereiten...",
  "Messung läuft..." (+Zeit),
  ("Messung pausiert"),
  "Messung beendet",
  "Messung abgebrochen" (weil Verbindung abgerissen)

**Comment by Madmaeckes** [comment]
Wird ausgelagert.
Footer besitzt setter für Text und Farbe von Messungs- sowie Verbindungsstatus.

**Comment by Madmaeckes** [comment]
Neue Klasse GuiAktualisieren setzt nun die Status, siehe Issue #12 .
