### ISSUE TITLE
Menü

### ISSUE THREAD

**Issue by MickyRosa** [Madmaeckes/VTfx#4]
Menü anlegen mit Buttons für:
- Verbinden/Trennen
- Messung starten/beenden
- (Messung pausieren/fortsetzen?)
- (speichern / laden)  //version 2b
- Einstellungen

**Comment by Madmaeckes** [comment]
@MickyRosa @Germilito 
Ich finde buttons für messung starten/beenden und verbinden/trennen sowie pausiren/fortsetzen in nemm menü eigentlich falsch untergebracht

**Comment by Germilito** [comment]
wo denn sonst? extra buttons? wenn ja würd ich das eh in buttons und im menü halten

**Comment by Madmaeckes** [comment]
Erledigt:
-  Verbinden/Trennen
-  Einstellungen

Offen:
- Messung starten/beenden
- (Messung pausieren/fortsetzen?)
- (speichern / laden) //version 2b
