### ISSUE TITLE
Geschwindigkeitsanzeige

### ISSUE THREAD

**Issue by MickyRosa** [Madmaeckes/VTfx#6]
Die Geschwindigkeitsanzeige auf dem ersten Reiter braucht:
- große Anzeige für Modellgeschwindigkeit
- kleine Anzeige für Vorbildgeschwindigkeit

Interface: jeweils ein double-setter

Style: Tacho wäre cool, vielleicht aber eher uncool weil sich die Werte nur sporadisch ändern.
Bin für eine Digitalanzeige like this:
[http://harmoniccode.blogspot.de/2013/11/enzo-part-i.html](url)

**Comment by Madmaeckes** [comment]
Done:
- große Anzeige für Modellgeschwindigkeit

TODO:
- kleine Anzeige für Vorbildgeschwindigkeit
